
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/benalexander/Desktop/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x700")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 700,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    600.0,
    350.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=7.0,
    y=186.0,
    width=73.0,
    height=59.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=14.0,
    y=92.0,
    width=65.0,
    height=59.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=5.0,
    y=284.0,
    width=74.0,
    height=64.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=579.0,
    y=187.0,
    width=115.0,
    height=31.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    637.0,
    394.0,
    image=image_image_2
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    637.5,
    415.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#14152C",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=558.0,
    y=404.0,
    width=159.0,
    height=21.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    637.5,
    528.0,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#14152C",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=558.0,
    y=517.0,
    width=159.0,
    height=20.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    637.5,
    472.0,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#14152C",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=558.0,
    y=461.0,
    width=159.0,
    height=20.0
)

canvas.create_text(
    606.0,
    382.0,
    anchor="nw",
    text="Tracking:",
    fill="#FFFFFF",
    font=("Nunito Bold", 10 * -1)
)

canvas.create_text(
    613.0,
    439.0,
    anchor="nw",
    text="Carrier:",
    fill="#FFFFFF",
    font=("Nunito Bold", 10 * -1)
)

canvas.create_text(
    613.0,
    495.0,
    anchor="nw",
    text="Status:",
    fill="#FFFFFF",
    font=("Nunito Bold", 10 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    636.0,
    307.0,
    image=image_image_3
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    644.5,
    149.49999999999997,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#14152C",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=469.0,
    y=134.99999999999994,
    width=351.0,
    height=27.000000000000043
)
window.resizable(False, False)
window.mainloop()
